[package]

name = "error-chain"
version = "0.5.0"
authors = [ "Brian Anderson <banderson@mozilla.com>",
            "Paul Colomiets <paul@colomiets.name>",
            "Colin Kiegel <kiegel@gmx.de>"]
description = "Yet another error boilerplate library"

documentation = "http://brson.github.io/error-chain/index.html"
homepage = "https://github.com/brson/error-chain"
repository = "https://github.com/brson/error-chain"

license = "MIT OR Apache-2.0"

[dependencies]
backtrace = "0.2.1"
